Stream mod download into a file
MForster/factorio-rust-tools pull request #77
Opened 2022-11-27 18:45 UTC by Builditluc

Linked to #74

2022-11-27 18:49 UTC, Builditluc commented
It seems there is an issue with [ModPortalClient::get_mod_spec](https://cs.github.com/MForster/factorio-rust-tools/blob/56c917652ae4479a99ba87a215d635040ef7584d/crates/factorio-mod-api/src/lib.rs#L47), so I cannot test this. Returned error:

```sh
Error:
	0: Error while talking to the API Server
	1: error decoding response body: missing field `changelog` at line 1 column 27
	2: missing field `changelog` at line 1 column 27

Location:
	crates/factorio-cli/src/commands/download_mod.rs:30
```

2022-11-27 20:02 UTC, MForster commented
> It seems there is an issue with [ModPortalClient::get_mod_spec](https://cs.github.com/MForster/factorio-rust-tools/blob/56c917652ae4479a99ba87a215d635040ef7584d/crates/factorio-mod-api/src/lib.rs#L47), so I cannot test this. 

Hm. Not sure where this is coming from. The changelog is documented to not be optional. Can you dump the reponse JSON to see what's going on? Maybe the API changed or is documented incorrectly?

If the server does indeed return valid responses without a changelog, I think we should change the type to optional.

2022-11-27 20:02 UTC, MForster requested changes

2022-11-27 20:04 UTC, MForster commented on crates/factorio-mod-api/Cargo.toml
> +sha1 = "0.10.0"
What's that needed for?

2022-11-27 20:50 UTC, MForster commented
Ah, one more thing, can you please also add an entry to `CHANGELOG.md`?

2022-11-28 07:13 UTC, MForster commented
> ```shell
> Error:
> 	0: Error while talking to the API Server
> 	1: error decoding response body: missing field `changelog` at line 1 column 27
> 	2: missing field `changelog` at line 1 column 27
> ```

Looking into that a bit more, I suspect that this is just an unhandled 404 (see #79) . I think you've used "Krastorio 2" as an example before, bute the mod is actually called "Krastorio2", without a space. Could that be it?

Yes, the error handling needs improving...

2022-11-28 18:29 UTC, Builditluc commented on crates/factorio-mod-api/Cargo.toml
> +sha1 = "0.10.0"
Oh sorry, that's not needed. I just experimented with validating the downloaded file but that would add way to much complexity

2022-11-28 18:40 UTC, Builditluc commented on crates/factorio-mod-api/src/lib.rs
> +            file.write(&chunk)?;
Because I somehow cannot install rustc 1.65.1 (`rustup update` only installs 1.61.0) I cannot run clippy myself, but I should've fixed the error

2022-11-28 18:51 UTC, Builditluc commented
>  bute the mod is actually called "Krastorio2",

yes, that was the issue, the mod now downloads correctly. Regarding error handling, I think it would be best to first implement some testing system

2022-11-29 09:14 UTC, MForster approved these changes
Thanks for the fixes. This looks good to go now!

> Regarding error handling, I think it would be best to first implement some testing system

Agreed.

2022-11-29 09:15 UTC, merged